version: 2

updates:
  - package-ecosystem: "npm"
    directories: "packages/*"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "npm dependencies"
      - "frontend"